[pytest]
asyncio_mode = auto
testpaths = tests app
norecursedirs = patient-app doctor-app venv .git node_modules
markers =
    not_needs_db: mark test as not requiring a real database connection
    needs_db: mark test as requiring a real database connection
