services:
  - type: web
    name: hospyn-api
    env: docker
    region: ohio
    plan: free
    branch: main
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: USE_REDIS
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: TWO_FACTOR_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SARVAM_KEY
        sync: false
      - key: JWT_PRIVATE_KEY
        sync: false
      - key: JWT_PUBLIC_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
