"""Add doctor verification session table

Revision ID: 61f0cb3f76c4
Revises: 3c2204a57135
Create Date: 2026-03-15 11:46:55.077977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f0cb3f76c4'
down_revision: Union[str, Sequence[str], None] = '3c2204a57135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_verification_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('state_medical_council', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('aadhaar_url', sa.String(length=255), nullable=True),
    sa.Column('selfie_url', sa.String(length=255), nullable=True),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('otp', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_verification_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_verification_sessions_session_id'), ['session_id'], unique=True)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        op.execute(sa.text('ALTER TABLE medical_records ADD COLUMN IF NOT EXISTS record_checksum VARCHAR(255)'))
        batch_op.create_index(batch_op.f('ix_medical_records_record_checksum'), ['record_checksum'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_medical_records_record_checksum'))
        batch_op.drop_column('record_checksum')

    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_doctor_verification_sessions_session_id'))
        op.execute(sa.text('DROP INDEX IF EXISTS ix_doctor_verification_sessions_id'))

    op.drop_table('doctor_verification_sessions')
    # ### end Alembic commands ###
