"""Implement unified ERP billing and revenue ledger

Revision ID: 82186647dea4
Revises: f5f3fc8dc49c
Create Date: 2026-05-15 12:00:48.673794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '82186647dea4'
down_revision: Union[str, Sequence[str], None] = 'f5f3fc8dc49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.Uuid(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('payable_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'DRAFT', 'PARTIALLY_PAID', 'VOID', name='paymentstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['patient_visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_patient_id'), ['patient_id'], unique=False)

    op.create_table('bill_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_category', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_items_invoice_id'), ['invoice_id'], unique=False)

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('clinical_ai_events', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('clinician_overrides', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('daily_hospital_metrics', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('medical_devices', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('patient_dashboards', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('patient_risk_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.Enum('CASH', 'UPI', 'CARD', 'NET_BANKING', 'INSURANCE', 'OTHER', name='paymentmethod'), nullable=False))
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'DRAFT', 'PARTIALLY_PAID', 'VOID', name='paymentstatus'),
               existing_nullable=False)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('idempotency_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('metadata_json',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_foreign_key('fk_payments_invoice_id_invoices', 'invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('pharmacy_stock', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock_ledger', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('tele_consultations', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('tele_consultations', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock_ledger', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.alter_column('metadata_json',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('idempotency_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'DRAFT', 'PARTIALLY_PAID', 'VOID', name='paymentstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('payment_method')
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patient_risk_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patient_dashboards', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('medical_devices', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('daily_hospital_metrics', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('clinician_overrides', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('clinical_ai_events', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_items_invoice_id'))

    op.drop_table('bill_items')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_patient_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_hospital_id'))

    op.drop_table('invoices')
    # ### end Alembic commands ###
