"""Add Ward Management and Admission Status Enum

Revision ID: 84248e251aa0
Revises: f8f6916564d1
Create Date: 2026-05-16 01:31:47.831778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add Ward Management and Admission Status Enum

Revision ID: 84248e251aa0
Revises: f8f6916564d1
Create Date: 2026-05-16 01:31:47.831778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84248e251aa0'
down_revision: Union[str, Sequence[str], None] = 'f8f6916564d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SHIELD V10: Postgres Enum Resilience
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'admissionstatus') THEN CREATE TYPE admissionstatus AS ENUM ('PENDING', 'ADMITTED', 'DISCHARGED'); END IF; END $$")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    
    # Cast admissions.status to admissionstatus enum on Postgres
    if bind.dialect.name == 'postgresql':
        op.execute("ALTER TABLE admissions ALTER COLUMN status TYPE admissionstatus USING status::admissionstatus")

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('clinical_ai_events', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('clinician_overrides', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('daily_hospital_metrics', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('lab_test_master', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('medical_devices', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('patient_dashboards', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('patient_risk_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_inventory', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock_ledger', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('tele_consultations', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('tele_consultations', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock_ledger', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_inventory', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patient_risk_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patient_dashboards', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('medical_devices', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('lab_test_master', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('daily_hospital_metrics', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('clinician_overrides', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('clinical_ai_events', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'ADMITTED', 'DISCHARGED', name='admissionstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
