"""Consolidate Clinical Enterprise Schema

Revision ID: 893c889454ff
Revises: 7fe81c25f628
Create Date: 2026-05-14 19:00:48.167308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893c889454ff'
down_revision: Union[str, Sequence[str], None] = '7fe81c25f628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('ai_summaries', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_member_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('hospital_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('added_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_allergies_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('signature', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('hospital_id', sa.UUID(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('resource_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('clinical_ai_events', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('clinician_overrides', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_member_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('hospital_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('added_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               existing_nullable=False)
        batch_op.alter_column('source_record_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_conditions_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])

    with op.batch_alter_table('daily_hospital_metrics', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('doctor_access', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('doctor_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('access_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('read', 'write', name='accesslevelenum'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('requested', 'granted', 'revoked', name='accessstatusenum'),
               existing_nullable=False)

    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'basic_verified', 'identity_verified', 'otp_verified', 'completed', name='verificationstatusenum'),
               existing_nullable=False)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('license_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'verified', 'rejected', name='licensestatusenum'),
               existing_nullable=False)

    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('medical_devices', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('family_member_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('record_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hospital_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('record_checksum', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('ocr_confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('needs_verification', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verified_by_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('malware_scan_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('hospital_id', sa.UUID(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('document', 'scan', 'vitals', 'prescription', 'lab_report', name='recordtypeenum'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_medical_records_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_record_checksum'), ['record_checksum'], unique=False)
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'doctors', ['verified_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_member_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('hospital_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('added_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               existing_nullable=False)
        batch_op.alter_column('source_record_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medications_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('doctor_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('alert', 'message', 'consent_request', 'consent_granted', 'system', name='notificationtypeenum'),
               existing_nullable=False)

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('patient_dashboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_member_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('hospital_id', sa.UUID(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_patient_dashboards_family_member_id'), ['family_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_dashboards_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_dashboards_patient_id'), ['patient_id'], unique=False)
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'])
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])

    with op.batch_alter_table('patient_risk_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hospital_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_patients_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock_ledger', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('tele_consultations', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('insforge_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hospyn_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('patient', 'doctor', 'admin', 'nurse', 'pharmacy', 'hospital_admin', name='roleenum'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_hospyn_id'), ['hospyn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_insforge_id'), ['insforge_id'], unique=True)

    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_insforge_id'))
        batch_op.drop_index(batch_op.f('ix_users_hospyn_id'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('patient', 'doctor', 'admin', 'nurse', 'pharmacy', 'hospital_admin', name='roleenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('token_version')
        batch_op.drop_column('hospyn_id')
        batch_op.drop_column('insforge_id')
        batch_op.drop_column('version_id')

    with op.batch_alter_table('tele_consultations', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock_ledger', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('pharmacy_stock', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patients_hospital_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('hospital_id')
        batch_op.drop_column('version_id')

    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patient_risk_profiles', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patient_dashboards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patient_dashboards_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_dashboards_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_patient_dashboards_family_member_id'))
        batch_op.alter_column('patient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('hospital_id')
        batch_op.drop_column('family_member_id')

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('alert', 'message', 'consent_request', 'consent_granted', 'system', name='notificationtypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('doctor_user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medications_hospital_id'))
        batch_op.alter_column('source_record_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('added_by',
               existing_type=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('hospital_id')
        batch_op.drop_column('family_member_id')

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medical_records_record_checksum'))
        batch_op.drop_index(batch_op.f('ix_medical_records_hospital_id'))
        batch_op.alter_column('type',
               existing_type=sa.Enum('document', 'scan', 'vitals', 'prescription', 'lab_report', name='recordtypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('hospital_id')
        batch_op.drop_column('malware_scan_status')
        batch_op.drop_column('verified_by_id')
        batch_op.drop_column('needs_verification')
        batch_op.drop_column('ocr_confidence_score')
        batch_op.drop_column('record_checksum')
        batch_op.drop_column('hospital_name')
        batch_op.drop_column('record_name')
        batch_op.drop_column('family_member_id')
        batch_op.drop_column('version_id')

    with op.batch_alter_table('medical_devices', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('license_status',
               existing_type=sa.Enum('pending', 'verified', 'rejected', name='licensestatusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('version_id')

    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'basic_verified', 'identity_verified', 'otp_verified', 'completed', name='verificationstatusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('doctor_access', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('requested', 'granted', 'revoked', name='accessstatusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('access_level',
               existing_type=sa.Enum('read', 'write', name='accesslevelenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('doctor_user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('daily_hospital_metrics', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conditions_hospital_id'))
        batch_op.alter_column('source_record_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('added_by',
               existing_type=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('hospital_id')
        batch_op.drop_column('family_member_id')

    with op.batch_alter_table('clinician_overrides', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('clinical_ai_events', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('resource_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('hospital_id')
        batch_op.drop_column('prev_hash')
        batch_op.drop_column('signature')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_allergies_hospital_id'))
        batch_op.alter_column('added_by',
               existing_type=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('hospital_id')
        batch_op.drop_column('family_member_id')

    with op.batch_alter_table('ai_summaries', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('hospital_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
