"""add token_version to users

Revision ID: 9317d6acb6e0
Revises: 1bc750f88bb4
Create Date: 2026-05-07 09:33:39.717928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9317d6acb6e0'
down_revision: Union[str, Sequence[str], None] = '1bc750f88bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('function_name', sa.String(length=100), nullable=False),
    sa.Column('args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_failures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_failures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_failures_job_id'), ['job_id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messageroleenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

    op.create_table('queue_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('checked_in', 'waiting_vitals', 'waiting_doctor', 'consultation', 'pharmacy', 'completed', 'cancelled', name='queuestatusenum'), nullable=False),
    sa.Column('token_number', sa.Integer(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_entries_id'), ['id'], unique=False)

    op.create_table('staff_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_profiles_id'), ['id'], unique=False)

    op.create_table('record_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('doctor_query', sa.String(length=255), nullable=False),
    sa.Column('doctor_user_id', sa.Integer(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accessed', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_shares_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_shares_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_shares_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_shares_share_token'), ['share_token'], unique=True)

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=255), nullable=True))
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_audit_logs_patient_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               existing_nullable=False)

    with op.batch_alter_table('doctor_access', schema=None) as batch_op:
        batch_op.alter_column('access_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('read', 'write', name='accesslevelenum'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('requested', 'granted', 'revoked', name='accessstatusenum'),
               existing_nullable=False)

    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'basic_verified', 'identity_verified', 'otp_verified', 'completed', name='verificationstatusenum'),
               existing_nullable=False)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False))
        batch_op.alter_column('license_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'verified', 'rejected', name='licensestatusenum'),
               existing_nullable=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('document', 'scan', 'vitals', 'prescription', 'lab_report', name='recordtypeenum'),
               existing_nullable=False)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('alert', 'message', 'consent_request', 'consent_granted', 'system', name='notificationtypeenum'),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('insforge_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('patient', 'doctor', 'admin', 'nurse', 'pharmacy', 'hospital_admin', name='roleenum'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_insforge_id'), ['insforge_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_insforge_id'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('patient', 'doctor', 'admin', 'nurse', 'pharmacy', 'hospital_admin', name='roleenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('token_version')
        batch_op.drop_column('insforge_id')
        batch_op.drop_column('version_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('version_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('alert', 'message', 'consent_request', 'consent_granted', 'system', name='notificationtypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('document', 'scan', 'vitals', 'prescription', 'lab_report', name='recordtypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('version_id')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('license_status',
               existing_type=sa.Enum('pending', 'verified', 'rejected', name='licensestatusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('version_id')

    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'basic_verified', 'identity_verified', 'otp_verified', 'completed', name='verificationstatusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('doctor_access', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('requested', 'granted', 'revoked', name='accessstatusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('access_level',
               existing_type=sa.Enum('read', 'write', name='accesslevelenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_patient_id'), ['patient_id'], unique=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('resource_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('prev_hash')
        batch_op.drop_column('signature')

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('record_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_shares_share_token'))
        batch_op.drop_index(batch_op.f('ix_record_shares_record_id'))
        batch_op.drop_index(batch_op.f('ix_record_shares_patient_id'))
        batch_op.drop_index(batch_op.f('ix_record_shares_id'))

    op.drop_table('record_shares')
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_profiles_id'))

    op.drop_table('staff_profiles')
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_entries_id'))

    op.drop_table('queue_entries')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    with op.batch_alter_table('job_failures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_failures_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_failures_id'))

    op.drop_table('job_failures')
    # ### end Alembic commands ###
