"""add token_version to users

Revision ID: 9317d6acb6e0
Revises: 1bc750f88bb4
Create Date: 2026-05-07 09:33:39.717928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9317d6acb6e0'
down_revision: Union[str, Sequence[str], None] = '1bc750f88bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    



    



    with op.batch_alter_table('allergies', schema=None) as batch_op:

        batch_op.alter_column('added_by',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)



    with op.batch_alter_table('audit_logs', schema=None) as batch_op:

        op.execute(sa.text('ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS signature VARCHAR(255)'))

        op.execute(sa.text('ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS prev_hash VARCHAR(255)'))

        batch_op.alter_column('resource_type',

               existing_type=sa.VARCHAR(length=100),

               type_=sa.String(length=50),

               existing_nullable=False)

        batch_op.alter_column('ip_address',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(length=45),

               existing_nullable=True)

        batch_op.alter_column('user_agent',

               existing_type=sa.TEXT(),

               type_=sa.String(length=255),

               existing_nullable=True)

        op.execute(sa.text('DROP INDEX IF EXISTS ix_audit_logs_patient_id'))

        op.execute(sa.text('DROP INDEX IF EXISTS ix_audit_logs_resource_id'))

        op.execute(sa.text('DROP INDEX IF EXISTS ix_audit_logs_user_id'))




    with op.batch_alter_table('conditions', schema=None) as batch_op:

        batch_op.alter_column('added_by',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)



    with op.batch_alter_table('doctor_access', schema=None) as batch_op:

        batch_op.alter_column('access_level',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)

        batch_op.alter_column('status',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)



    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:

        batch_op.alter_column('status',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)



    with op.batch_alter_table('doctors', schema=None) as batch_op:

        op.execute(sa.text('ALTER TABLE doctors ADD COLUMN IF NOT EXISTS version_id INTEGER'))

        batch_op.alter_column('license_status',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)



    with op.batch_alter_table('medical_records', schema=None) as batch_op:

        op.execute(sa.text('ALTER TABLE medical_records ADD COLUMN IF NOT EXISTS version_id INTEGER'))

        batch_op.alter_column('type',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)



    with op.batch_alter_table('medications', schema=None) as batch_op:

        batch_op.alter_column('added_by',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)



    with op.batch_alter_table('notifications', schema=None) as batch_op:

        batch_op.alter_column('type',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)



    with op.batch_alter_table('patients', schema=None) as batch_op:

        op.execute(sa.text('ALTER TABLE patients ADD COLUMN IF NOT EXISTS version_id INTEGER'))



    with op.batch_alter_table('users', schema=None) as batch_op:

        op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS version_id INTEGER'))

        op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS insforge_id VARCHAR(255)'))

        op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS token_version INTEGER'))

        batch_op.alter_column('role',

               existing_type=sa.VARCHAR(length=50),

               type_=sa.String(50),

               existing_nullable=False)




    # ### end Alembic commands ###





def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_users_insforge_id'))
        batch_op.alter_column('role',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('token_version')
        batch_op.drop_column('insforge_id')
        batch_op.drop_column('version_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('version_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('version_id')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('license_status',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('version_id')

    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('doctor_access', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('access_level',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_audit_logs_action'))
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('resource_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('prev_hash')
        batch_op.drop_column('signature')

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.String(50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('record_shares', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_record_shares_share_token'))
        op.execute(sa.text('DROP INDEX IF EXISTS ix_record_shares_record_id'))
        op.execute(sa.text('DROP INDEX IF EXISTS ix_record_shares_patient_id'))
        op.execute(sa.text('DROP INDEX IF EXISTS ix_record_shares_id'))

    op.drop_table('record_shares')
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_staff_profiles_id'))

    op.drop_table('staff_profiles')
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_queue_entries_id'))

    op.drop_table('queue_entries')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_messages_user_id'))
        op.execute(sa.text('DROP INDEX IF EXISTS ix_messages_id'))
        op.execute(sa.text('DROP INDEX IF EXISTS ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_departments_id'))

    op.drop_table('departments')
    with op.batch_alter_table('job_failures', schema=None) as batch_op:
        op.execute(sa.text('DROP INDEX IF EXISTS ix_job_failures_job_id'))
        op.execute(sa.text('DROP INDEX IF EXISTS ix_job_failures_id'))

    op.drop_table('job_failures')
    # ### end Alembic commands ###