"""Hospyn_2_0_Master_Clinical_Schema

Revision ID: 94ae1a4c2cea
Revises: 
Create Date: 2026-05-14 22:22:26.183600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.core.encryption import StringEncryptedType, TextEncryptedType

# revision identifiers, used by Alembic.
revision: str = '94ae1a4c2cea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_job_tracker',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_reason', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_job_tracker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_job_tracker_resource_id'), ['resource_id'], unique=False)

    op.create_table('doctor_verification_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('state_medical_council', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'basic_verified', 'identity_verified', 'otp_verified', 'completed', name='verificationstatusenum'), nullable=False),
    sa.Column('aadhaar_url', sa.String(length=255), nullable=True),
    sa.Column('selfie_url', sa.String(length=255), nullable=True),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('otp', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_verification_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_verification_sessions_session_id'), ['session_id'], unique=True)

    op.create_table('hospitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospyn_id', sa.String(length=50), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('org_type', sa.Enum('hospital', 'pharmacy', 'lab', name='organizationtypeenum'), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitals_hospyn_id'), ['hospyn_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_hospitals_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitals_registration_number'), ['registration_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_hospitals_short_code'), ['short_code'], unique=True)

    op.create_table('job_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('function_name', sa.String(length=100), nullable=False),
    sa.Column('args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_failures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_failures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_failures_job_id'), ['job_id'], unique=False)

    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('otp', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_verifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_verifications_identifier'), ['identifier'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('insforge_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', 'nurse', 'pharmacy', 'hospital_admin', name='roleenum'), nullable=False),
    sa.Column('hospyn_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_hospyn_id'), ['hospyn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_insforge_id'), ['insforge_id'], unique=True)

    op.create_table('clinical_ai_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_template', sa.String(length=255), nullable=False),
    sa.Column('prompt_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('safety_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('safety_mode', sa.Enum('informational', 'clinical_assist', 'restricted', 'emergency', 'human_only', name='aisafetymode'), nullable=False),
    sa.Column('policy_filters_applied', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_ai_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_ai_events_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_ai_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_ai_events_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_ai_events_user_id'), ['user_id'], unique=False)

    op.create_table('daily_hospital_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('pharmacy_revenue', sa.Float(), nullable=False),
    sa.Column('insurance_pending_amount', sa.Float(), nullable=False),
    sa.Column('total_patients_seen', sa.Integer(), nullable=False),
    sa.Column('average_wait_time_minutes', sa.Float(), nullable=False),
    sa.Column('bed_occupancy_rate', sa.Float(), nullable=False),
    sa.Column('total_prescriptions_issued', sa.Integer(), nullable=False),
    sa.Column('critical_alerts_triggered', sa.Integer(), nullable=False),
    sa.Column('metadata_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_hospital_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_hospital_metrics_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_hospital_metrics_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_status', sa.Enum('pending', 'verified', 'rejected', name='licensestatusenum'), nullable=False),
    sa.Column('license_copy_url', sa.String(length=255), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_id'), ['id'], unique=False)

    op.create_table('medical_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.Enum('SCANNER', 'MONITOR', 'LAB_ANALYZER', 'WEARABLE', name='devicetype'), nullable=False),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('last_ping', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_devices_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_devices_serial_number'), ['serial_number'], unique=True)

    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messageroleenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('safety_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_trace_id'), ['trace_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hospyn_id', sa.String(length=50), nullable=False),
    sa.Column('phone_number', StringEncryptedType(length=255), nullable=False),
    sa.Column('date_of_birth', StringEncryptedType(length=255), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_hospyn_id'), ['hospyn_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)

    op.create_table('pharmacy_stock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('min_stock_level', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pharmacy_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacy_stock_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_stock_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_stock_medication_name'), ['medication_name'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('items_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('total_estimated_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_name'), ['supplier_name'], unique=False)

    op.create_table('ai_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('one_page_summary', TextEncryptedType(), nullable=False),
    sa.Column('patient_summary', TextEncryptedType(), nullable=False),
    sa.Column('doctor_summary', TextEncryptedType(), nullable=False),
    sa.Column('structured_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_summaries_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=False),
    sa.Column('prev_hash', sa.String(length=255), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('beds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('bed_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'occupied', 'cleaning', 'maintenance', name='bedstatusenum'), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('last_modified_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beds_bed_number'), ['bed_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_beds_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beds_id'), ['id'], unique=False)

    op.create_table('clinician_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('ai_event_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_user_id', sa.Uuid(), nullable=False),
    sa.Column('override_type', sa.String(length=50), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('correction_text', sa.Text(), nullable=True),
    sa.Column('severity_impact', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_event_id'], ['clinical_ai_events.id'], ),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinician_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinician_overrides_ai_event_id'), ['ai_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinician_overrides_doctor_user_id'), ['doctor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinician_overrides_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinician_overrides_id'), ['id'], unique=False)

    op.create_table('digital_prescriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'fulfilled', 'cancelled', 'expired', name='prescriptionstatusenum'), nullable=False),
    sa.Column('medications', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', TextEncryptedType(), nullable=True),
    sa.Column('qr_code_id', sa.String(length=100), nullable=False),
    sa.Column('signature_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pharmacist_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digital_prescriptions_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_prescriptions_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_prescriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_prescriptions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_prescriptions_qr_code_id'), ['qr_code_id'], unique=True)

    op.create_table('doctor_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_user_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('access_level', sa.Enum('read', 'write', name='accesslevelenum'), nullable=False),
    sa.Column('status', sa.Enum('requested', 'granted', 'revoked', name='accessstatusenum'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_access_id'), ['id'], unique=False)

    op.create_table('family_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('linked_hospyn_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_members_patient_id'), ['patient_id'], unique=False)

    op.create_table('fhir_resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('fhir_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_device_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_device_id'], ['medical_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fhir_resources_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_resources_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_resources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_resources_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_resources_resource_type'), ['resource_type'], unique=False)

    op.create_table('notification_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_queue_patient_id'), ['patient_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('doctor_user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('alert', 'message', 'consent_request', 'consent_granted', 'system', name='notificationtypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('patient_risk_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('readmission_risk', sa.Float(), nullable=False),
    sa.Column('critical_deterioration_risk', sa.Float(), nullable=False),
    sa.Column('no_show_risk', sa.Float(), nullable=False),
    sa.Column('risk_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('clinical_priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_risk_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_risk_profiles_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_risk_profiles_patient_id'), ['patient_id'], unique=True)

    op.create_table('patient_visits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('visit_reason', TextEncryptedType(), nullable=False),
    sa.Column('symptoms', TextEncryptedType(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'active', 'completed', 'cancelled', name='visitstatusenum'), nullable=False),
    sa.Column('queue_token', sa.String(length=50), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_visits_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_visits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_visits_patient_id'), ['patient_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_provider_transaction_id'), ['provider_transaction_id'], unique=False)

    op.create_table('pharmacy_stock_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('INWARD', 'OUTWARD', 'ADJUSTMENT', name='stockmovementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['pharmacy_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pharmacy_stock_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacy_stock_ledger_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_stock_ledger_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_stock_ledger_stock_id'), ['stock_id'], unique=False)

    op.create_table('queue_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('checked_in', 'waiting_vitals', 'waiting_doctor', 'consultation', 'pharmacy', 'completed', 'cancelled', name='queuestatusenum'), nullable=False),
    sa.Column('token_number', sa.Integer(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_entries_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_entries_id'), ['id'], unique=False)

    op.create_table('queue_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'EMERGENCY_OVERRIDE', name='queuetokenstatus'), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('last_modified_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_tokens_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_tokens_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_tokens_patient_id'), ['patient_id'], unique=False)

    op.create_table('staff_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_profiles_id'), ['id'], unique=False)

    op.create_table('tele_consultations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'MISSED', name='teleconsultstatus'), nullable=False),
    sa.Column('meeting_provider', sa.String(length=50), nullable=False),
    sa.Column('meeting_id', sa.String(length=255), nullable=False),
    sa.Column('meeting_url', sa.String(length=512), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    with op.batch_alter_table('tele_consultations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tele_consultations_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tele_consultations_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tele_consultations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tele_consultations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tele_consultations_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('wearable_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('data_type', sa.Enum('HEART_RATE', 'STEPS', 'SLEEP', 'SPO2', 'BLOOD_GLUCOSE', name='wearabledatatype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wearable_data_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wearable_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wearable_data_measured_at'), ['measured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wearable_data_patient_id'), ['patient_id'], unique=False)

    op.create_table('admissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('queue_token_id', sa.Uuid(), nullable=True),
    sa.Column('bed_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('last_modified_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['queue_token_id'], ['queue_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admissions_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_patient_id'), ['patient_id'], unique=False)

    op.create_table('allergies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=True),
    sa.Column('allergen', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('added_by', sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'), nullable=False),
    sa.Column('confirmed_by_patient', sa.Boolean(), nullable=False),
    sa.Column('hidden_by_patient', sa.Boolean(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allergies_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allergies_id'), ['id'], unique=False)

    op.create_table('clinical_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_events_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_events_aggregate_type'), ['aggregate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_events_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('insurance_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('tpa_name', sa.String(length=100), nullable=False),
    sa.Column('policy_number', StringEncryptedType(length=100), nullable=False),
    sa.Column('claim_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_claims_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_claims_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_claims_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_claims_tpa_name'), ['tpa_name'], unique=False)

    op.create_table('medical_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('document', 'scan', 'vitals', 'prescription', 'lab_report', name='recordtypeenum'), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('raw_text', TextEncryptedType(), nullable=True),
    sa.Column('ai_extracted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ai_summary', TextEncryptedType(), nullable=True),
    sa.Column('patient_summary', TextEncryptedType(), nullable=True),
    sa.Column('doctor_summary', TextEncryptedType(), nullable=True),
    sa.Column('record_name', sa.String(length=255), nullable=True),
    sa.Column('hospital_name', sa.String(length=255), nullable=True),
    sa.Column('hidden_by_patient', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_checksum', sa.String(length=64), nullable=True),
    sa.Column('ocr_confidence_score', sa.Float(), nullable=True),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('malware_scan_status', sa.String(length=50), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_record_checksum'), ['record_checksum'], unique=False)

    op.create_table('patient_dashboards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=True),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_dashboards_family_member_id'), ['family_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_dashboards_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_dashboards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_dashboards_patient_id'), ['patient_id'], unique=False)

    op.create_table('prescription_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['pharmacy_stock.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['digital_prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_items_prescription_id'), ['prescription_id'], unique=False)

    op.create_table('conditions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=True),
    sa.Column('name', StringEncryptedType(length=255), nullable=False),
    sa.Column('added_by', sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'), nullable=False),
    sa.Column('confirmed_by_patient', sa.Boolean(), nullable=False),
    sa.Column('hidden_by_patient', sa.Boolean(), nullable=False),
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conditions_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conditions_id'), ['id'], unique=False)

    op.create_table('lab_diagnostic_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ordered', 'sample_collected', 'processing', 'completed', 'rejected', name='laborderstatusenum'), nullable=False),
    sa.Column('tests', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('clinical_history', TextEncryptedType(), nullable=True),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('ai_risk_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_diagnostic_orders_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_diagnostic_orders_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_diagnostic_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_diagnostic_orders_patient_id'), ['patient_id'], unique=False)

    op.create_table('lab_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=True),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('observation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_results_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_test_name'), ['test_name'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=True),
    sa.Column('generic_name', StringEncryptedType(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.Enum('patient', 'doctor', 'ai', 'nurse', 'system', name='addedbyenum'), nullable=False),
    sa.Column('confirmed_by_patient', sa.Boolean(), nullable=False),
    sa.Column('hidden_by_patient', sa.Boolean(), nullable=False),
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_id'), ['id'], unique=False)

    op.create_table('record_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_query', sa.String(length=255), nullable=False),
    sa.Column('doctor_user_id', sa.Uuid(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accessed', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_shares_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_shares_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_shares_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_shares_share_token'), ['share_token'], unique=True)

    op.create_table('medication_intake_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_intake_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_intake_logs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_intake_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_intake_logs_id'))

    op.drop_table('medication_intake_logs')
    with op.batch_alter_table('record_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_shares_share_token'))
        batch_op.drop_index(batch_op.f('ix_record_shares_record_id'))
        batch_op.drop_index(batch_op.f('ix_record_shares_patient_id'))
        batch_op.drop_index(batch_op.f('ix_record_shares_id'))

    op.drop_table('record_shares')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_id'))
        batch_op.drop_index(batch_op.f('ix_medications_hospital_id'))

    op.drop_table('medications')
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_results_test_name'))
        batch_op.drop_index(batch_op.f('ix_lab_results_record_id'))
        batch_op.drop_index(batch_op.f('ix_lab_results_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_results_id'))
        batch_op.drop_index(batch_op.f('ix_lab_results_hospital_id'))

    op.drop_table('lab_results')
    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_diagnostic_orders_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_diagnostic_orders_id'))
        batch_op.drop_index(batch_op.f('ix_lab_diagnostic_orders_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_lab_diagnostic_orders_doctor_id'))

    op.drop_table('lab_diagnostic_orders')
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conditions_id'))
        batch_op.drop_index(batch_op.f('ix_conditions_hospital_id'))

    op.drop_table('conditions')
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_items_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_prescription_items_id'))

    op.drop_table('prescription_items')
    with op.batch_alter_table('patient_dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_dashboards_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_dashboards_id'))
        batch_op.drop_index(batch_op.f('ix_patient_dashboards_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_patient_dashboards_family_member_id'))

    op.drop_table('patient_dashboards')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_record_checksum'))
        batch_op.drop_index(batch_op.f('ix_medical_records_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_hospital_id'))

    op.drop_table('medical_records')
    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_claims_tpa_name'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_patient_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_hospital_id'))

    op.drop_table('insurance_claims')
    with op.batch_alter_table('clinical_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_clinical_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_events_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_events_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_clinical_events_aggregate_type'))
        batch_op.drop_index(batch_op.f('ix_clinical_events_aggregate_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_events_actor_id'))

    op.drop_table('clinical_events')
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allergies_id'))
        batch_op.drop_index(batch_op.f('ix_allergies_hospital_id'))

    op.drop_table('allergies')
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admissions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_hospital_id'))

    op.drop_table('admissions')
    with op.batch_alter_table('wearable_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wearable_data_patient_id'))
        batch_op.drop_index(batch_op.f('ix_wearable_data_measured_at'))
        batch_op.drop_index(batch_op.f('ix_wearable_data_id'))
        batch_op.drop_index(batch_op.f('ix_wearable_data_hospital_id'))

    op.drop_table('wearable_data')
    with op.batch_alter_table('tele_consultations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tele_consultations_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_tele_consultations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_tele_consultations_id'))
        batch_op.drop_index(batch_op.f('ix_tele_consultations_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_tele_consultations_doctor_id'))

    op.drop_table('tele_consultations')
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_profiles_id'))

    op.drop_table('staff_profiles')
    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_tokens_patient_id'))
        batch_op.drop_index(batch_op.f('ix_queue_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_queue_tokens_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_queue_tokens_department_id'))

    op.drop_table('queue_tokens')
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_entries_id'))
        batch_op.drop_index(batch_op.f('ix_queue_entries_hospital_id'))

    op.drop_table('queue_entries')
    with op.batch_alter_table('pharmacy_stock_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacy_stock_ledger_stock_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_stock_ledger_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_stock_ledger_hospital_id'))

    op.drop_table('pharmacy_stock_ledger')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_provider_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_payments_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))
        batch_op.drop_index(batch_op.f('ix_payments_hospital_id'))

    op.drop_table('payments')
    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_visits_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_visits_id'))
        batch_op.drop_index(batch_op.f('ix_patient_visits_hospital_id'))

    op.drop_table('patient_visits')
    with op.batch_alter_table('patient_risk_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_risk_profiles_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_risk_profiles_hospital_id'))

    op.drop_table('patient_risk_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('notification_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_queue_patient_id'))

    op.drop_table('notification_queue')
    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_resources_resource_type'))
        batch_op.drop_index(batch_op.f('ix_fhir_resources_patient_id'))
        batch_op.drop_index(batch_op.f('ix_fhir_resources_id'))
        batch_op.drop_index(batch_op.f('ix_fhir_resources_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_fhir_resources_external_id'))

    op.drop_table('fhir_resources')
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_members_patient_id'))
        batch_op.drop_index(batch_op.f('ix_family_members_id'))

    op.drop_table('family_members')
    with op.batch_alter_table('doctor_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_access_id'))

    op.drop_table('doctor_access')
    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digital_prescriptions_qr_code_id'))
        batch_op.drop_index(batch_op.f('ix_digital_prescriptions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_digital_prescriptions_id'))
        batch_op.drop_index(batch_op.f('ix_digital_prescriptions_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_digital_prescriptions_doctor_id'))

    op.drop_table('digital_prescriptions')
    with op.batch_alter_table('clinician_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinician_overrides_id'))
        batch_op.drop_index(batch_op.f('ix_clinician_overrides_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_clinician_overrides_doctor_user_id'))
        batch_op.drop_index(batch_op.f('ix_clinician_overrides_ai_event_id'))

    op.drop_table('clinician_overrides')
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beds_id'))
        batch_op.drop_index(batch_op.f('ix_beds_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_beds_bed_number'))

    op.drop_table('beds')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_patient_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_summaries_id'))

    op.drop_table('ai_summaries')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_name'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_hospital_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('pharmacy_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacy_stock_medication_name'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_stock_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_stock_hospital_id'))

    op.drop_table('pharmacy_stock')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_id'))
        batch_op.drop_index(batch_op.f('ix_patients_hospyn_id'))
        batch_op.drop_index(batch_op.f('ix_patients_hospital_id'))

    op.drop_table('patients')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_trace_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_processed'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_event_type'))

    op.drop_table('outbox_events')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('medical_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_devices_serial_number'))
        batch_op.drop_index(batch_op.f('ix_medical_devices_id'))
        batch_op.drop_index(batch_op.f('ix_medical_devices_hospital_id'))

    op.drop_table('medical_devices')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_id'))

    op.drop_table('doctors')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    with op.batch_alter_table('daily_hospital_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_hospital_metrics_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_daily_hospital_metrics_date'))

    op.drop_table('daily_hospital_metrics')
    with op.batch_alter_table('clinical_ai_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_ai_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_ai_events_trace_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_ai_events_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_ai_events_hospital_id'))

    op.drop_table('clinical_ai_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_insforge_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_hospyn_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_verifications_identifier'))
        batch_op.drop_index(batch_op.f('ix_otp_verifications_id'))

    op.drop_table('otp_verifications')
    with op.batch_alter_table('job_failures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_failures_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_failures_id'))

    op.drop_table('job_failures')
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_short_code'))
        batch_op.drop_index(batch_op.f('ix_hospitals_registration_number'))
        batch_op.drop_index(batch_op.f('ix_hospitals_name'))
        batch_op.drop_index(batch_op.f('ix_hospitals_hospyn_id'))

    op.drop_table('hospitals')
    with op.batch_alter_table('doctor_verification_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_verification_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_verification_sessions_id'))

    op.drop_table('doctor_verification_sessions')
    with op.batch_alter_table('clinical_job_tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_job_tracker_resource_id'))

    op.drop_table('clinical_job_tracker')
    # ### end Alembic commands ###
