"""encrypt patient pii fields

Revision ID: de35bd572117
Revises: bcc066933201
Create Date: 2026-03-13 21:58:21.754663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.encryption


# revision identifiers, used by Alembic.
revision: str = 'de35bd572117'
down_revision: Union[str, Sequence[str], None] = 'bcc066933201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=app.core.encryption.StringEncryptedType(length=255),
               existing_nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.VARCHAR(length=20),
               type_=app.core.encryption.StringEncryptedType(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=app.core.encryption.StringEncryptedType(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=app.core.encryption.StringEncryptedType(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
